@host = https://localhost:5001

POST {{host}}/Authorize  HTTP/1.1
Content-Type: application/x-www-form-urlencoded

username=WilsonPan&password=123456
# {
#     "username":"WilsonPan",
#     "password":"123456"
# }


###
GET  {{host}}/WeatherForecast HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IldpbHNvblBhbiIsImVtYWlsIjoid2lsc29ucGFuQGdpdGh1Yi5jb20iLCJleHAiOjE1OTE2NzQ5MDEsImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjUwMDEiLCJhdWQiOiJXaWxzb25QYW4ifQ.9NX3nsaI9NKe3lcknjYlJxnDGnPmcZKiC9caVjm_sxY

